# Generated by Django 5.1.1 on 2024-09-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='wind_speed',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
